steps:
- name: golang
  args: ['go', 'version']
- name: golang
  args: ['go', 'test']
  dir: 'functions/archivefanfic'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'archivefanfic', '--trigger-http', '--runtime', 'go119']
  dir: 'functions/archivefanfic'