steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/archivefanfic'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'archivefanfic', '--gen2', '--trigger-http', '--runtime', 'nodejs18', '--region=europe-west4', '--source=.', '--entry-point=ArchiveFanfic']
  dir: 'functions/archivefanfic'