steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args: 
    - -c
    - |
      git fetch --depth=2 origin master
      git --no-pager diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g' > /workspace/diff.txt
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args: 
    - -c
    - |
       while read line
       do 
       config="${line}/cloudbuild.yaml"
       echo $config
       if [[ ! -f "${config}" ]]; then
        echo "no such file"
        continue
       fi
       gcloud builds submit $line --config=${config}
       done < /workspace/diff.txt