steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      cp devops/known_hosts.github /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args: 
    - -c
    - |
      git fetch --depth=2 origin master
      git --no-pager diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g' > /workspace/diff.txt
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args: 
    - -c
    - |
       while read line
       do 
       config="${line}/cloudbuild.yaml"
       echo $config
       if [[ ! -f "${config}" ]]; then
        echo "no such file"
        continue
       fi
       gcloud builds submit $line --config=${config}
       done < /workspace/diff.txt
    volumes:
    - name: 'ssh'
      path: /root/.ssh