steps:
- name: golang
  args: ['go', 'version']
- name: golang
  args: ['go', 'test']
  dir: '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'queuefanfic', '--trigger-http', '--runtime', 'go119']
  dir: '.'