steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/updatebucketstats'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'updatebucketstats', '--gen2', '--trigger-http', 
    '--runtime', 'nodejs18', '--region=europe-west4', 
    '--source=.', '--entry-point=UpdateBucketStats',
    '--set-secrets=OBJECT_SECRET_KEY=${_OBJECT_SECRET_KEY_ID}:${_OBJECT_SECRET_KEY_VERSION}',
    '--set-env-vars=OBJECT_ACCESS_KEY=${_OBJECT_ACCESS_KEY},OBJECT_REGION=${_OBJECT_REGION},OBJECT_NAME=${_OBJECT_NAME},OBJECT_ENDPOINT=${_OBJECT_ENDPOINT}']
  dir: 'functions/updatebucketstats'